import type { AppData } from './types';

export const mockData: AppData = {
  venues: [
    {
      id: 'venue-club-gimnasio',
      name: 'Gimnasio Club Modelo',
      city: 'Buenos Aires',
      ceilingHeightM: 8.5,
      usableLengthM: 32,
      usableWidthM: 18,
      notes: 'Techo plano, algunas corrientes cerca de la puerta lateral.',
    },
    {
      id: 'venue-hangar',
      name: 'Hangar Escuela',
      city: 'Moron',
      ceilingHeightM: 12,
      usableLengthM: 45,
      usableWidthM: 25,
      notes: 'Mayor volumen, cuidado con vigas longitudinales.',
    },
  ],
  models: [
    {
      id: 'model-f1m-a',
      name: 'F1M Azul',
      wingspanMm: 455,
      weightG: 3.15,
      wingAreaDm2: 13.8,
      wingLeadingEdgeHeightMm: 42,
      wingTrailingEdgeHeightMm: 38,
      stabilizerLeadingEdgeHeightMm: 31,
      stabilizerTrailingEdgeHeightMm: 32,
      cgFromWingLeadingEdgeMm: 48,
      notes: 'Modelo principal para trimado indoor.',
    },
    {
      id: 'model-f1m-b',
      name: 'F1M Liviano Experimental',
      wingspanMm: 460,
      weightG: 3.05,
      wingAreaDm2: 14.1,
      wingLeadingEdgeHeightMm: 43,
      wingTrailingEdgeHeightMm: 39,
      stabilizerLeadingEdgeHeightMm: 31,
      stabilizerTrailingEdgeHeightMm: 32,
      cgFromWingLeadingEdgeMm: 47,
    },
  ],
  propellers: [
    {
      id: 'prop-vp-01',
      name: 'VP 145 mm resorte medio',
      type: 'variable_pitch',
      diameterMm: 145,
      maxPitchMm: 620,
      minPitchMm: 430,
      springHardness: 5,
      vpMechanismMode: 'known',
      bladeMaterial: 'balsa',
      notes: 'Helice VP baseline para gimnasio bajo.',
    },
    {
      id: 'prop-vp-02',
      name: 'VP 150 mm resorte blando',
      type: 'variable_pitch',
      diameterMm: 150,
      maxPitchMm: 650,
      minPitchMm: 410,
      springHardness: 4,
      vpMechanismMode: 'unknown',
      bladeMaterial: 'balsa',
    },
  ],
  rubberBatches: [
    {
      id: 'batch-may-2026',
      name: 'Mayo 2026 - lote A',
      manufacturer: 'Tan Super Sport',
      widthMm: 1.5,
      thicknessMm: 1,
      purchaseDate: '2026-05-01',
      notes: 'Cortar y pesar antes de armar motores finales.',
    },
  ],
  motors: [
    {
      id: 'motor-001',
      name: 'Motor 1.35 g / 420 mm',
      batchId: 'batch-may-2026',
      loopLengthMm: 420,
      weightG: 1.35,
      strands: 1,
      lubricant: 'Silicona',
    },
    {
      id: 'motor-002',
      name: 'Motor 1.48 g / 450 mm',
      batchId: 'batch-may-2026',
      loopLengthMm: 450,
      weightG: 1.48,
      strands: 1,
      lubricant: 'Silicona',
    },
  ],
  flights: [
    {
      id: 'flight-sample-001',
      date: '2026-05-10T10:00:00.000Z',
      venueId: 'venue-club-gimnasio',
      modelId: 'model-f1m-a',
      propellerId: 'prop-vp-01',
      motorId: 'motor-001',
      turnsLoaded: 1100,
      backOff: 80,
      durationSec: 235,
      maxAltitudeM: 7.2,
      touchedCeiling: false,
      timeToCeilingSec: undefined,
      ceilingContactDurationSec: 0,
      secondClimb: false,
      secondCeilingTouch: false,
      secondCeilingContactDurationSec: 0,
      turnPattern: 'left',
      climb: 'good',
      stability: 'stable',
      landing: 'soft',
      propType: 'variable_pitch',
      rpmVisual: 'normal',
      rpmSamples: [
        { timeSec: 0, rpm: 4200, note: 'lanzamiento' },
        { timeSec: 90, rpm: 3300, note: 'trepada' },
        { timeSec: 170, rpm: 2600, note: 'planeo' },
        { timeSec: 235, rpm: 2100, note: 'final' },
      ],
      rpmInitial: 4200,
      rpmMid: 2600,
      rpmFinal: 2100,
      vpPropeller: {
        maxPitchMm: 620,
        minPitchMm: 430,
        springHardness: 5,
        notes: 'Configuracion media para gimnasio bajo.',
      },
      vpTransitionObserved: 'normal',
      vpMechanismMode: 'known',
      vpTransitionTimeSec: 110,
      rpmBeforeVpTransition: 3200,
      rpmAfterVpTransition: 2950,
      launchTorque: 0.42,
      descentStartSec: 190,
      descentStartTorque: 0.08,
      turnsAtDescentStart: 210,
      remainingTurns: 160,
      notes: 'Vuelo limpio, margen de techo moderado.',
    },
  ],
  sessions: [],
  flightConfigurations: [],
  configurationChanges: [],
  optimalConfigurations: [],
};
